import { Manrope } from "next/font/google";

import { Providers } from "@/app/lib/providers";

import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Craco-crac",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <Providers>
      <html lang="en">
        <body className={manrope.className}>{children}</body>
      </html>
    </Providers>
  );
}